In [1]:
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [2]:
complexTensor = np.arange(7*5*2).reshape(7,5,2)
print(complexTensor.shape)
complexTensor

(7, 5, 2)


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69]]])

In [5]:
# Transpose 수행 시 axis를 입력하지 않으면, numpy Library에서 설정된 default값을 출력한다
# l * n * m -> m * n * l 이 default
# Transpose = n * m -> m * n 으로의 변환을 수행
# Transpose => shape permutation(permutation : 순열 순서가 부여된 임의의 집합을 다른 순서로 뒤섞는 연산)
transposeTensor = np.transpose(complexTensor)
print(transposeTensor)
print(transposeTensor.shape)

[[[ 0 10 20 30 40 50 60]
  [ 2 12 22 32 42 52 62]
  [ 4 14 24 34 44 54 64]
  [ 6 16 26 36 46 56 66]
  [ 8 18 28 38 48 58 68]]

 [[ 1 11 21 31 41 51 61]
  [ 3 13 23 33 43 53 63]
  [ 5 15 25 35 45 55 65]
  [ 7 17 27 37 47 57 67]
  [ 9 19 29 39 49 59 69]]]
(2, 5, 7)


In [6]:
# 즉, 내가 원하는 대로 axis를 변환하여 transpose 하려면 axis를 명시적으로 지정해야 한다.
transposeTensor2 = np.transpose(complexTensor, [1, 2, 0])
print(transposeTensor2)
print(transposeTensor2.shape)

[[[ 0 10 20 30 40 50 60]
  [ 1 11 21 31 41 51 61]]

 [[ 2 12 22 32 42 52 62]
  [ 3 13 23 33 43 53 63]]

 [[ 4 14 24 34 44 54 64]
  [ 5 15 25 35 45 55 65]]

 [[ 6 16 26 36 46 56 66]
  [ 7 17 27 37 47 57 67]]

 [[ 8 18 28 38 48 58 68]
  [ 9 19 29 39 49 59 69]]]
(5, 2, 7)
